<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SetupController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\TeacherController;
use App\Http\Controllers\Authenticates;
use App\Http\Controllers\AuditTrialController;
use App\Http\Controllers\Roles;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});


Route::post("LogIn",[Authenticates::class,"LogIn"]);
Route::post("ChangeDefaultPassword",[Authenticates::class,"ChangeDefaultPassword"]);
Route::get("Unlocker/{UserId}",[Authenticates::class,"Unlocker"]);
Route::get("ViewResetPassword/{UserId}",[Authenticates::class,"ViewResetPassword"]);
Route::get("HeartBeat/{UserId}",[Authenticates::class,"HeartBeat"]);
Route::get("DashBoardChecker/{SessionID}",[Authenticates::class,"DashBoardChecker"]);
Route::post("GetAuthFile",[Authenticates::class,"GetAuthFile"]);
Route::post("BulkAutoGeneratedAuthenticators",[Authenticates::class,"BulkAutoGeneratedAuthenticators"]);




Route::get("generatePDF",[AuditTrialController::class,"generatePDF"]);







Route::post("Setup",[SetupController::class,"Setup"]);
Route::post("LocalSetup",[SetupController::class,"LocalSetup"]);
Route::post("CompanyToken",[SetupController::class,"CompanyToken"]);
Route::post("LocalCompanyToken",[SetupController::class,"LocalCompanyToken"]);
Route::get("SystemRoles",[SetupController::class,"SystemRoles"]);


Route::post("RegisterStudent",[StudentController::class,"RegisterStudent"]);
Route::post("UpdateStudent",[StudentController::class,"UpdateStudent"]);
Route::post("BulkRegisterStudent",[StudentController::class,"BulkRegisterStudent"]);
Route::post("BulkAutoGeneratedRegisterStudent",[StudentController::class,"BulkAutoGeneratedRegisterStudent"]);
Route::get("GetStudent/{StudentId}/{CompanyId}",[StudentController::class,"GetStudent"]);
Route::post("GetStudentInAClass",[StudentController::class,"GetStudentInAClass"]);
Route::post("GetStudentInAClassFile",[StudentController::class,"GetStudentInAClassFile"]);
Route::post("GetStudentInASchool",[StudentController::class,"GetStudentInASchool"]);
Route::post("GetStudentInSchoolFile",[StudentController::class,"GetStudentInSchoolFile"]);
Route::delete("DeleteStudent/{StudentId}/{CompanyId}",[StudentController::class,"DeleteStudent"]);


Route::post("RegisterTeachers",[TeacherController::class,"RegisterTeachers"]);
Route::post("UpdateTeachers",[TeacherController::class,"UpdateTeachers"]);
Route::post("GetTeachersInASchool",[TeacherController::class,"GetTeachersInASchool"]);
Route::post("BulkRegisterTeacher",[TeacherController::class,"BulkRegisterTeacher"]);
Route::post("GetTeacherInSchoolFile",[TeacherController::class,"GetTeacherInSchoolFile"]);
Route::post("UploadAutoGeneratedRegisterTeacher",[TeacherController::class,"UploadAutoGeneratedRegisterTeacher"]);
Route::get("ViewTeacher/{TeacherId}/{CompanyId}",[TeacherController::class,"ViewTeacher"]);
Route::delete("DeleteTeacher/{TeacherId}/{CompanyId}",[TeacherController::class,"DeleteTeacher"]);


Route::post("CreatePrimaryRole",[Roles::class,"CreatePrimaryRole"]);
Route::post("DeletePrimaryRole",[Roles::class,"DeletePrimaryRole"]);
//Route::post("CreateUserDetailedRole",[Roles::class,"CreateUserDetailedRole"]);
Route::post("CreateAnotherUserDetailedRole",[Roles::class,"CreateAnotherUserDetailedRole"]);
Route::post("ViewUserDetailedRole",[Roles::class,"ViewUserDetailedRole"]);
Route::post("DeleteUserDetailedRole",[Roles::class,"DeleteUserDetailedRole"]);
Route::post("CreateUserSummaryRole",[Roles::class,"CreateUserSummaryRole"]);
Route::post("DeleteUserSummaryRole",[Roles::class,"DeleteUserSummaryRole"]);

Route::post("CreateRoleName",[Roles::class,"CreateRoleName"]);
Route::post("DeleteRoleName",[Roles::class,"DeleteRoleName"]);





