<?php

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\SetupController;
use App\Http\Controllers\StudentController;
use App\Http\Controllers\StaffMembersController;
use App\Http\Controllers\Authenticates;
use App\Http\Controllers\AuditTrialController;
use App\Http\Controllers\Roles;
use App\Http\Controllers\TransportController;

/*
|--------------------------------------------------------------------------
| API Routes
|--------------------------------------------------------------------------
|
| Here is where you can register API routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "api" middleware group. Make something great!
|
*/

Route::middleware('auth:sanctum')->get('/user', function (Request $request) {
    return $request->user();
});


Route::post("LogIn",[Authenticates::class,"LogIn"]);
Route::post("ChangeDefaultPassword",[Authenticates::class,"ChangeDefaultPassword"]);
Route::get("Unlocker/{UserId}",[Authenticates::class,"Unlocker"]);
Route::get("ViewResetPassword/{UserId}",[Authenticates::class,"ViewResetPassword"]);
Route::get("HeartBeat/{UserId}",[Authenticates::class,"HeartBeat"]);
Route::get("DashBoardChecker/{SessionID}",[Authenticates::class,"DashBoardChecker"]);
Route::post("GetAuthFile",[Authenticates::class,"GetAuthFile"]);
Route::post("BulkAutoGeneratedAuthenticators",[Authenticates::class,"BulkAutoGeneratedAuthenticators"]);






Route::post("SoftwareRegistration",[SetupController::class,"SoftwareRegistration"]);
Route::post("SubscriptionManagement",[SetupController::class,"SubscriptionManagement"]);

Route::post("LocalSetup",[SetupController::class,"LocalSetup"]);
Route::post("LocalCompanyToken",[SetupController::class,"LocalCompanyToken"]);
Route::get("SystemRoles",[SetupController::class,"SystemRoles"]);
Route::get("PermissionMgmt",[SetupController::class,"PermissionMgmt"]);
Route::get("RegistrationMgmt",[SetupController::class,"RegistrationMgmt"]);
Route::get("ViewSchoolData",[SetupController::class,"ViewSchoolData"]);




Route::post("RegisterStudent",[StudentController::class,"RegisterStudent"]);
Route::post("UpdateStudent",[StudentController::class,"UpdateStudent"]);
Route::post("BulkRegisterStudent",[StudentController::class,"BulkRegisterStudent"]);
Route::post("BulkAutoGeneratedRegisterStudent",[StudentController::class,"BulkAutoGeneratedRegisterStudent"]);
Route::get("GetStudent/{StudentId}/{CompanyId}/{SenderId}",[StudentController::class,"GetStudent"]);
Route::post("GetStudentInAClass",[StudentController::class,"GetStudentInAClass"]);
Route::post("GetStudentInAClassFile",[StudentController::class,"GetStudentInAClassFile"]);
Route::post("GetStudentInASchool",[StudentController::class,"GetStudentInASchool"]);
Route::post("GetStudentInSchoolFile",[StudentController::class,"GetStudentInSchoolFile"]);
Route::delete("DeleteStudent/{StudentId}/{CompanyId}/{SenderId}",[StudentController::class,"DeleteStudent"]);


Route::post("RegisterStaffMemberss",[StaffMembersController::class,"RegisterStaffMemberss"]);
Route::post("UpdateStaffMemberss",[StaffMembersController::class,"UpdateStaffMemberss"]);
Route::post("GetStaffMemberssInASchool",[StaffMembersController::class,"GetStaffMemberssInASchool"]);
Route::post("BulkRegisterStaffMembers",[StaffMembersController::class,"BulkRegisterStaffMembers"]);
Route::post("GetStaffMembersInSchoolFile",[StaffMembersController::class,"GetStaffMembersInSchoolFile"]);
Route::post("UploadAutoGeneratedRegisterStaffMembers",[StaffMembersController::class,"UploadAutoGeneratedRegisterStaffMembers"]);
Route::get("ViewStaffMembers/{StaffId}/{CompanyId}",[StaffMembersController::class,"ViewStaffMembers"]);
Route::delete("DeleteStaffMembers/{StaffId}/{CompanyId}",[StaffMembersController::class,"DeleteStaffMembers"]);


Route::post("CreatePrimaryRole",[Roles::class,"CreatePrimaryRole"]);
Route::post("DeletePrimaryRole",[Roles::class,"DeletePrimaryRole"]);
//Route::post("CreateUserDetailedRole",[Roles::class,"CreateUserDetailedRole"]);
Route::post("CreateAnotherUserDetailedRole",[Roles::class,"CreateAnotherUserDetailedRole"]);
Route::post("ViewUserDetailedRole",[Roles::class,"ViewUserDetailedRole"]);
Route::post("DeleteUserDetailedRole",[Roles::class,"DeleteUserDetailedRole"]);
Route::post("CreateUserSummaryRole",[Roles::class,"CreateUserSummaryRole"]);
Route::post("DeleteUserSummaryRole",[Roles::class,"DeleteUserSummaryRole"]);

Route::post("CreateRoleName",[Roles::class,"CreateRoleName"]);
Route::post("DeleteRoleName",[Roles::class,"DeleteRoleName"]);


Route::post("AddStudentToTransportList",[TransportController::class,"AddStudentToTransportList"]);
Route::post("EditStudentInTransportList",[TransportController::class,"EditStudentInTransportList"]);
Route::post("GetAllTransportUsers",[TransportController::class,"GetAllTransportUsers"]);
Route::post("DeleteStudentInTransportList",[TransportController::class,"DeleteStudentInTransportList"]);
Route::post("StudentToPickupList",[TransportController::class,"StudentToPickupList"]);
Route::post("PickUp",[TransportController::class,"PickUp"]);
Route::post("StudentToDepartureList",[TransportController::class,"StudentToDepartureList"]);
Route::post("Departure",[TransportController::class,"Departure"]);
Route::post("StudentToDestinationArrival",[TransportController::class,"StudentToDestinationArrival"]);
Route::post("DestinationArrival",[TransportController::class,"DestinationArrival"]);





