<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\Teacher;
use Carbon\Carbon;
use App\Models\Authentic;
use App\Http\Controllers\AuditTrialController;
use App\Jobs\BulkTeachersRegistration;
use App\Jobs\UploadingAutoGeneratedTeacherList;
use App\Exports\TeachersExport;

class TeacherController extends Controller
{
  
    protected $audit;

    public function __construct(AuditTrialController $auditTrialController)
    {
        $this->audit = $auditTrialController;
    }

    function RegisterTeachers(Request $req){

        $response = $this->audit->PrepaidMeter($req->CompanyId);

        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }

        $t = new Teacher();

        if($req->filled("CompanyId")){
            $t->CompanyId = $req->CompanyId;
        }

        $t->save();


        $t->TeacherId = strval(10000 + $t->id);


        if($req->hasFile("ProfilePic")){
            $t->ProfilePic = $req->file("ProfilePic")->store("","public");
        }

        if($req->hasFile("Cert1")){
            $t->Cert1 = $req->file("Cert1")->store("","public");
        }

        if($req->hasFile("Cert2")){
            $t->Cert2 = $req->file("Cert2")->store("","public");
        }

        if($req->hasFile("IdCards")){
            $t->IdCards = $req->file("IdCards")->store("","public");
        }
       
        
        

        if($req->filled("FirstName")){
            $t->FirstName  = $req ->FirstName  ;
        }

        if($req->filled("OtherName")){
            $t->OtherName  = $req ->OtherName  ;
        }

        if($req->filled("LastName")){
            $t->LastName  = $req ->LastName  ;
        }

        if($req->filled("DateOfBirth")){
            $t->DateOfBirth  = $req ->DateOfBirth  ;
        }

        if($req->filled("Gender")){
            $t->Gender  = $req ->Gender  ;
        }

        if($req->filled("HomeTown")){
            $t->HomeTown  = $req ->HomeTown  ;
        }

        if($req->filled("Location")){
            $t->Location  = $req ->Location  ;
        }

        if($req->filled("Country")){
            $t->Country  = $req ->Country  ;
        }

        if($req->filled("MaritalStatus")){
            $t->MaritalStatus  = $req ->MaritalStatus  ;
        }

        if($req->filled("PhoneNumber")){
            $t->PhoneNumber  = $req ->PhoneNumber  ;
        }

        if($req->filled("Email")){
            $t->Email  = $req ->Email  ;
        }

        if($req->filled("HighestEducationalLevel")){
            $t->HighestEducationalLevel  = $req ->HighestEducationalLevel  ;
        }

        if($req->filled("TeachingExperience")){
            $t->TeachingExperience  = $req ->TeachingExperience  ;
        }

        if($req->filled("TaxNumber")){
            $t->TaxNumber  = $req ->TaxNumber  ;
        }

        if($req->filled("SocialSecurity")){
            $t->SocialSecurity  = $req ->SocialSecurity  ;
        }
        if($req->filled("HealthStatus")){
            $t->HealthStatus  = $req ->HealthStatus  ;
        }
        if($req->filled("EmergencyPerson")){
            $t->EmergencyPerson  = $req ->EmergencyPerson  ;
        }
        if($req->filled("EmergencyPhone1")){
            $t->EmergencyPhone1  = $req ->EmergencyPhone1  ;
        }
        if($req->filled("EmergencyPhone2")){
            $t->EmergencyPhone2  = $req ->EmergencyPhone2  ;
        }
        
        $checker  = Teacher::where("SocialSecurity", $req->SocialSecurity)->where("CompanyId", $req->CompanyId)->first();
        if ($checker){
            return response()->json(["message"=>"Teacher Already Exist"],400);
        }

        $saver = $t->save();
        if($saver){



          //  $this->audit->TeacherAudit($t->TeacherId, $t->CompanyId, "Registered A Teacher");
        
            $UserName = t->FirstName." ".t->OtherName." ".t->LastName;
            $Password =  $this->audit->IdGenerator();
          
            $this->audit->Authenticator(
                $t->TeacherId,
                $t->ProfilePic,
                "Teacher",
                $UserName,
                $Password,
                $t->CompanyId
            );



            return response()->json(["message"=>$t->Title.", ".$t->FirstName." ".$t->OtherName." ".$t->LastName." has been Employed"],200);
        }
        else{
            return response()->json(["message"=>"An error has occured"],400);
        }



    }

    function UpdateTeachers(Request $req){

        $response = $this->audit->PrepaidMeter($req->CompanyId);

        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }

        $t = Teacher::where("TeacherId", $req->TeacherId)->where("CompanyId", $req->CompanyId)->first();
        if($t==null){
            return response()->json(["message"=>"Teacher not found"],400);
        }


        if($req->hasFile("ProfilePic")){
            $t->ProfilePic = $req->file("ProfilePic")->store("","public");
        }

        if($req->hasFile("Cert1")){
            $t->Cert1 = $req->file("Cert1")->store("","public");
        }

        if($req->hasFile("Cert2")){
            $t->Cert2 = $req->file("Cert2")->store("","public");
        }

        if($req->hasFile("IdCards")){
            $t->IdCards = $req->file("IdCards")->store("","public");
        }
       
        
        

        if($req->filled("FirstName")){
            $t->FirstName  = $req ->FirstName  ;
        }

        if($req->filled("OtherName")){
            $t->OtherName  = $req ->OtherName  ;
        }

        if($req->filled("LastName")){
            $t->LastName  = $req ->LastName  ;
        }

        if($req->filled("DateOfBirth")){
            $t->DateOfBirth  = $req ->DateOfBirth  ;
        }

        if($req->filled("Gender")){
            $t->Gender  = $req ->Gender  ;
        }

        if($req->filled("HomeTown")){
            $t->HomeTown  = $req ->HomeTown  ;
        }

        if($req->filled("Location")){
            $t->Location  = $req ->Location  ;
        }

        if($req->filled("Country")){
            $t->Country  = $req ->Country  ;
        }

        if($req->filled("MaritalStatus")){
            $t->MaritalStatus  = $req ->MaritalStatus  ;
        }

        if($req->filled("PhoneNumber")){
            $t->PhoneNumber  = $req ->PhoneNumber  ;
        }

        if($req->filled("Email")){
            $t->Email  = $req ->Email  ;
        }

        if($req->filled("HighestEducationalLevel")){
            $t->HighestEducationalLevel  = $req ->HighestEducationalLevel  ;
        }

        if($req->filled("TeachingExperience")){
            $t->TeachingExperience  = $req ->TeachingExperience  ;
        }

        if($req->filled("TaxNumber")){
            $t->TaxNumber  = $req ->TaxNumber  ;
        }

        if($req->filled("SocialSecurity")){
            $t->SocialSecurity  = $req ->SocialSecurity  ;
        }
        if($req->filled("HealthStatus")){
            $t->HealthStatus  = $req ->HealthStatus  ;
        }
        if($req->filled("EmergencyPerson")){
            $t->EmergencyPerson  = $req ->EmergencyPerson  ;
        }
        if($req->filled("EmergencyPhone1")){
            $t->EmergencyPhone1  = $req ->EmergencyPhone1  ;
        }
        if($req->filled("EmergencyPhone2")){
            $t->EmergencyPhone2  = $req ->EmergencyPhone2  ;
        }
        

        $saver = $t->save();
        if($saver){
            return response()->json(["message"=>$t->Title.", ".$t->FirstName." ".$t->OtherName." ".$t->LastName." has been Employed"],200);
        }
        else{
            return response()->json(["message"=>"An error has occured"],400);
        }

        

    }

    function ViewTeacher($TeacherId,$CompanyId){
        $response = $this->audit->PrepaidMeter($CompanyId);

        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }

        $t = Teacher::where("TeacherId", $TeacherId)->where("CompanyId", $CompanyId)->first();
        if($t==null){
            return response()->json(["message"=>"Teacher not found"],400);
        }
        return $t;
    }

    function DeleteTeacher($TeacherId,$CompanyId){
        $response = $this->audit->PrepaidMeter($CompanyId);

        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }

        $t = Teacher::where("TeacherId", $TeacherId)->where("CompanyId", $CompanyId)->first();
        if($t==null){
            return response()->json(["message"=>"Teacher not found"],400);
        }
        $saver = $t->delete();
        if($saver){
            return response()->json(["message"=>"Teacher Deleted Successfully"],200);
        }
        else{
            return response()->json(["message"=>"An error has occured"],400);
        }


       
    }


    public function GetTeachersInASchool(Request $req)
    {
        $response = $this->audit->PrepaidMeter($req->CompanyId);
    
        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }
    
        $Teachers = Teacher::where("CompanyId", $req->CompanyId)
        ->orderBy('LastName')
        ->get()->toArray();
    
        return $Teachers;
    }

    public function BulkRegisterTeacher(Request $req)
    {
        $response = $this->audit->PrepaidMeter($req->CompanyId);
    
        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }
    
        if ($req->hasFile('excel_file')) {
            $file = $req->file('excel_file');
            $filePath = $file->getPathname();
    
            
               
            // Dispatch the job to process the bulk Teacher registration
            BulkTeachersRegistration::dispatch($filePath, $req->CompanyId);
            return response()->json(["message" => "File uploaded successfully. Teachers will be processed in the background."], 200);

        }
    
        return response()->json(["message" => "No file uploaded."], 400);
    }

    public function GetTeacherInSchoolFile(Request $req)
    {
        $response = $this->audit->PrepaidMeter($req->CompanyId);
    
        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }
    
        $Teachers = Teacher::where("CompanyId", $req->CompanyId)
            ->orderBy('LastName')
            ->get();
    
        return Excel::download(new TeachersExport($Teachers), 'EntireTeacherList.xlsx');
    }

    public function UploadAutoGeneratedRegisterTeacher(Request $req)
    {
        $response = $this->audit->PrepaidMeter($req->CompanyId);
    
        if ($response !== null && $response->getStatusCode() !== 200) {
            return $response;
        }
    
        if ($req->hasFile('excel_file')) {
            $file = $req->file('excel_file');
            $filePath = $file->getPathname();
    
            
               
            // Dispatch the job to process the bulk student registration
            UploadingAutoGeneratedTeacherList::dispatch($filePath, $req->CompanyId);
            return response()->json(["message" => "File uploaded successfully. Students will be processed in the background."], 200);

        }
    
        return response()->json(["message" => "No file uploaded."], 400);
    }








}
