<?php
namespace App\Jobs;

use App\Models\StaffMembers;
use Illuminate\Bus\Queueable;
use Illuminate\Contracts\Queue\ShouldQueue;
use Illuminate\Foundation\Bus\Dispatchable;
use Illuminate\Queue\InteractsWithQueue;
use Illuminate\Queue\SerializesModels;
use Maatwebsite\Excel\Facades\Excel;

class UploadingAutoGeneratedStaffMembersList implements ShouldQueue
{
    use Dispatchable, InteractsWithQueue, Queueable, SerializesModels;

    protected $filePath;
    protected $CompanyId;

    public function __construct($filePath, $CompanyId)
    {
        $this->filePath = $filePath;
        $this->CompanyId = $CompanyId;
    }

    public function handle()
{
    $rows = Excel::toArray([], $this->filePath, null, \Maatwebsite\Excel\Excel::XLSX);

    if (count($rows) > 0) {
        $headers = $rows[0][0]; // Assuming the headers are in the first row

        // Find the index of the StaffId column
        $StaffIdIndex = array_search('StaffId', $headers);

        if ($StaffIdIndex !== false) {
            for ($i = 1; $i < count($rows[0]); $i++) {
                $row = $rows[0][$i];

                // Check if StaffId is defined in the file
                $StaffId = isset($row[$StaffIdIndex]) ? $row[$StaffIdIndex] : null;

                // Check if StaffId already exists
                if (StaffMembers::where('StaffId', $StaffId)->where('CompanyId', $this->CompanyId)->exists()) {
                    continue; // Skip if the StaffId already exists
                }

                $s = new StaffMembers();

                // Assign values based on headers
                $s->CompanyId = $this->CompanyId;

                // Generate StaffId if not defined in the file
                $s->StaffId = $StaffId ? $StaffId : strval(10000 + $s->id);

                foreach ($headers as $index => $header) {
                    // Check if IsSuspended is null in the file, if so, set it to false
                    if ($header === 'IsSuspended' && is_null($row[$index])) {
                        $row[$index] = false;
                    }

                    $s->{$header} = $row[$index];
                }

                $s->save();
               
            }
        } else {
            // Handle case when StaffId column is not found in headers
            return response()->json(["message"=>"StaffId Does Not Exist"],400);
        }
    }
}

    
}
